name: Reddit Demand Mapper

on:
  schedule:
    - cron: "0 0 * * 0"   # Run every Sunday at 00:00 UTC
  workflow_dispatch:       # Allow manual runs too

jobs:
  run-mapper:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Reddit Demand Mapper
      - name: Run Reddit Demand Mapper
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        run: |
          python reddit-demand-mapper/reddit_demand_mapper.py

      # Step 5: Upload results as artifacts
      - name: Upload results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reddit-demand-mapper-results
          path: reddit-demand-mapper/reports/
