name: Reddit Demand Mapper

on:
  schedule:
    - cron: "0 0 * * 0"   # Run every Sunday at 00:00 UTC
  workflow_dispatch:       # Allow manual runs too

jobs:
  run-mapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw pandas python-dotenv

      - name: Run Reddit Demand Mapper
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        run: |
          python reddit_demand_mapper.py

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reddit-demand-reports
          path: reports/
